//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public string idBlog { get; set; }
        public string nameBlog { get; set; }
        public string shortContent { get; set; }
        public Nullable<System.DateTime> dateCurrent { get; set; }
        public string typeBlog { get; set; }
        public string img { get; set; }
        public string mainContent { get; set; }
        public Nullable<bool> isPassing { get; set; }
    }
}
