//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int id_sanpham { get; set; }
        public string id_giohang { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string tinhtrang { get; set; }
    }
}
