//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int id_donhang { get; set; }
        public int id_sanpham { get; set; }
        public Nullable<double> thanhtien { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual ProductInfo ProductInfo { get; set; }
        public virtual TheOrder TheOrder { get; set; }
    }
}
