//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_Category
    {
        public Pro_Category()
        {
            this.Product_Group = new HashSet<Product_Group>();
            this.ProductInfoes = new HashSet<ProductInfo>();
        }
    
        public string id_loai_sp { get; set; }
        public string tenloaisp { get; set; }
    
        public virtual ICollection<Product_Group> Product_Group { get; set; }
        public virtual ICollection<ProductInfo> ProductInfoes { get; set; }
    }
}
