//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public ProductInfo()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int id_sanpham { get; set; }
        public Nullable<double> giacu { get; set; }
        public Nullable<double> giamoi { get; set; }
        public string ten_sanpham { get; set; }
        public string id_loai_sanpham { get; set; }
        public string hinh_sanpham { get; set; }
        public string hinh_quatang { get; set; }
        public string thongtin_km { get; set; }
        public string id_nhomsp { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Pro_Category Pro_Category { get; set; }
        public virtual Product_Group Product_Group { get; set; }
    }
}
