//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductDBContext : DbContext
    {
        public ProductDBContext()
            : base("name=ProductDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cart> Carts { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Pro_Category> Pro_Category { get; set; }
        public DbSet<Product_Group> Product_Group { get; set; }
        public DbSet<ProductInfo> ProductInfoes { get; set; }
        public DbSet<RoleMaster> RoleMasters { get; set; }
        public DbSet<User_Web> User_Web { get; set; }
        public DbSet<UserRolesMapping> UserRolesMappings { get; set; }
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<TheOrder> TheOrders { get; set; }
    }
}
