//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Group
    {
        public Product_Group()
        {
            this.ProductInfoes = new HashSet<ProductInfo>();
        }
    
        public string id_loaisp { get; set; }
        public string id_nhomsp { get; set; }
        public string tennhom { get; set; }
    
        public virtual Pro_Category Pro_Category { get; set; }
        public virtual ICollection<ProductInfo> ProductInfoes { get; set; }
    }
}
