//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheOrder
    {
        public TheOrder()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int id_donhang { get; set; }
        public string tendondang { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string hinhthuc_thanhtoan { get; set; }
        public string Statuss { get; set; }
        public string tenkhachhang { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
