//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Web
    {
        public User_Web()
        {
            this.UserRolesMappings = new HashSet<UserRolesMapping>();
        }
    
        public int id_user { get; set; }
        public string ten_taikhoan { get; set; }
        public string matkhau { get; set; }
        public string SDT { get; set; }
        public string hoTen { get; set; }
    
        public virtual ICollection<UserRolesMapping> UserRolesMappings { get; set; }
    }
}
